# gentable.py
from datetime import date

from sqlalchemy import Date, Float, Integer, MetaData, Text
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    metadata = MetaData(schema="general")


class Mdt(Base):
    __tablename__ = "mdt"
    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    date: Mapped[date] = mapped_column(Date(), nullable=False)
    site: Mapped[str] = mapped_column(Text(), nullable=False)
    enodebid: Mapped[int] = mapped_column(Integer(), nullable=False)
    ci: Mapped[int] = mapped_column(Integer(), nullable=False)
    quadkey20: Mapped[float] = mapped_column(Float(), nullable=False)
    sample: Mapped[float] = mapped_column(Float(), nullable=False)
    rsrp_mean: Mapped[float] = mapped_column(Float(), nullable=False)
    rsrq_mean: Mapped[float] = mapped_column(Float(), nullable=False)
    rank: Mapped[float] = mapped_column(Float(), nullable=False)
    long_grid: Mapped[float] = mapped_column(Float(), nullable=False)
    lat_grid: Mapped[float] = mapped_column(Float(), nullable=False)


class Mcom(Base):
    __tablename__ = "mcom"
    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    site_id: Mapped[str] = mapped_column(Text(), nullable=False)
    node_id: Mapped[str] = mapped_column(Text(), nullable=False)
    ne_id: Mapped[str] = mapped_column(Text(), nullable=False)
    cell_name: Mapped[str] = mapped_column(Text(), nullable=True)
    site_name: Mapped[float] = mapped_column(Float(), nullable=True)
    longitude: Mapped[float] = mapped_column(Float(), nullable=True)
    latitude: Mapped[float] = mapped_column(Float(), nullable=True)
    dir: Mapped[int] = mapped_column(Integer(), nullable=True)
    antenna_height: Mapped[int] = mapped_column(Integer(), nullable=True)
    tower_height: Mapped[int] = mapped_column(Integer(), nullable=True)
    tilt: Mapped[str] = mapped_column(Text(), nullable=True)
    port_ret: Mapped[str] = mapped_column(Text(), nullable=True)
    tilt_mekanik: Mapped[int] = mapped_column(Integer(), nullable=True)
    tilt_elektrik: Mapped[int] = mapped_column(Integer(), nullable=True)
    tanggal_audit: Mapped[str] = mapped_column(Text(), nullable=True)
    remark: Mapped[str] = mapped_column(Text(), nullable=True)
    cell_type: Mapped[str] = mapped_column(Text(), nullable=True)
    ant_type: Mapped[str] = mapped_column(Text(), nullable=True)
    ant_bw: Mapped[int] = mapped_column(Integer(), nullable=True)
    ant_size: Mapped[int] = mapped_column(Integer(), nullable=True)
    tac: Mapped[int] = mapped_column(Integer(), nullable=True)
    cellid: Mapped[int] = mapped_column(Integer(), nullable=True)
    earfcn: Mapped[int] = mapped_column(Integer(), nullable=True)
    pci: Mapped[int] = mapped_column(Integer(), nullable=True)
    physicallayercellidgroup: Mapped[int] = mapped_column(Integer(), nullable=True)
    physicallayersubcellid: Mapped[int] = mapped_column(Integer(), nullable=True)
    rachrootsequence: Mapped[int] = mapped_column(Integer(), nullable=True)
    ip_oam: Mapped[float] = mapped_column(Float(), nullable=True)
    configuredpower: Mapped[str] = mapped_column(Text(), nullable=True)
    status: Mapped[str] = mapped_column(Text(), nullable=True)
    mcc_mnc: Mapped[str] = mapped_column(Text(), nullable=True)
    enbid: Mapped[float] = mapped_column(Float(), nullable=True)
    userlabel: Mapped[str] = mapped_column(Text(), nullable=True)
    bandwidth: Mapped[float] = mapped_column(Float(), nullable=True)
    update_date: Mapped[date] = mapped_column(Date(), nullable=True)
    board: Mapped[str] = mapped_column(Text(), nullable=True)
    tech: Mapped[str] = mapped_column(Text(), nullable=True)
    id_desa: Mapped[float] = mapped_column(Float(), nullable=True)
    desa: Mapped[str] = mapped_column(Text(), nullable=True)
    mc_class: Mapped[str] = mapped_column(Text(), nullable=True)
    id_kec: Mapped[float] = mapped_column(Float(), nullable=True)
    kecamatan: Mapped[str] = mapped_column(Text(), nullable=True)
    id_kab: Mapped[float] = mapped_column(Float(), nullable=True)
    kabupaten: Mapped[str] = mapped_column(Text(), nullable=True)
    provinsi: Mapped[str] = mapped_column(Text(), nullable=True)
    branch: Mapped[str] = mapped_column(Text(), nullable=True)
    cluster_sales: Mapped[str] = mapped_column(Text(), nullable=True)
    nop: Mapped[str] = mapped_column(Text(), nullable=True)
    tower_provider: Mapped[str] = mapped_column(Text(), nullable=True)
    type_area: Mapped[str] = mapped_column(Text(), nullable=True)
    lte: Mapped[str] = mapped_column(Text(), nullable=True)


class DailyLte(Base):
    __tablename__ = "daily_lte"
    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    date_id: Mapped[date] = mapped_column(Date(), nullable=True)
    erbs: Mapped[str] = mapped_column(Text(), nullable=False)
    siteid: Mapped[str] = mapped_column(Text(), nullable=False)
    neid: Mapped[str] = mapped_column(Text(), nullable=False)
    eutrancell: Mapped[str] = mapped_column(Text(), nullable=False)
    availability: Mapped[float] = mapped_column(Float(), nullable=True)
    rrc_sr: Mapped[float] = mapped_column(Float(), nullable=True)
    erab_sr: Mapped[float] = mapped_column(Float(), nullable=True)
    sssr: Mapped[float] = mapped_column(Float(), nullable=True)
    sar: Mapped[float] = mapped_column(Float(), nullable=True)
    s1_signaling_sr: Mapped[float] = mapped_column(Float(), nullable=True)
    intra_ho_exe_sr: Mapped[float] = mapped_column(Float(), nullable=True)
    inter_ho_exe_sr: Mapped[float] = mapped_column(Float(), nullable=True)
    downlink_traff_volume: Mapped[float] = mapped_column(Float(), nullable=True)
    uplink_traff_volume: Mapped[float] = mapped_column(Float(), nullable=True)
    total_traff_volume: Mapped[float] = mapped_column(Float(), nullable=True)
    payload_totalgb: Mapped[float] = mapped_column(Float(), nullable=True)
    dlresourceblockutilizingrate: Mapped[float] = mapped_column(Float(), nullable=True)
    ulresourceblockutilizingrate: Mapped[float] = mapped_column(Float(), nullable=True)
    lte_peak_active_dl_users: Mapped[float] = mapped_column(Float(), nullable=True)
    lte_peak_active_ul_users: Mapped[float] = mapped_column(Float(), nullable=True)
    ul_int_pusch: Mapped[float] = mapped_column(Float(), nullable=True)
    ul_int_pucch: Mapped[float] = mapped_column(Float(), nullable=True)
    celldownlinkaveragethroughput: Mapped[float] = mapped_column(Float(), nullable=True)
    celluplinkaveragethroughput: Mapped[float] = mapped_column(Float(), nullable=True)
    user_downlink_average_throughput_mbps: Mapped[float] = mapped_column(
        Float(), nullable=True
    )
    user_uplink_average_throughputmbps: Mapped[float] = mapped_column(
        Float(), nullable=True
    )
    se_daily: Mapped[float] = mapped_column(Float(), nullable=True)
    avgcqinonhom: Mapped[float] = mapped_column(Float(), nullable=True)
    cqi7: Mapped[float] = mapped_column(Float(), nullable=True)
    csfb_2g: Mapped[float] = mapped_column(Float(), nullable=True)
    csfb_3g: Mapped[float] = mapped_column(Float(), nullable=True)
    csfb_3g_sr: Mapped[float] = mapped_column(Float(), nullable=True)
    pagingsuccesrate: Mapped[float] = mapped_column(Float(), nullable=True)
    pagingdiscardrate: Mapped[float] = mapped_column(Float(), nullable=True)
    pmerabrelabnormalenbact_: Mapped[float] = mapped_column(Float(), nullable=True)
    maximum_user_number_rrc: Mapped[float] = mapped_column(Float(), nullable=True)
    rrc_connected_user: Mapped[float] = mapped_column(Float(), nullable=True)
    pmcelldowntimeauto_: Mapped[float] = mapped_column(Float(), nullable=True)
    psho_to_utran_exe_sr: Mapped[float] = mapped_column(Float(), nullable=True)
    ip_latency: Mapped[float] = mapped_column(Float(), nullable=True)
    active_user: Mapped[float] = mapped_column(Float(), nullable=True)
    pmcelldowntimeman_: Mapped[float] = mapped_column(Float(), nullable=True)
    erab_drop_rate: Mapped[float] = mapped_column(Float(), nullable=True)
    pmerabrelabnormalenbactcdt_: Mapped[float] = mapped_column(Float(), nullable=True)
    pmerabrelabnormalenbactho_: Mapped[float] = mapped_column(Float(), nullable=True)
    pmerabrelabnormalenbacthpr_: Mapped[float] = mapped_column(Float(), nullable=True)
    pmerabrelabnormalenbacttnfail_: Mapped[float] = mapped_column(
        Float(), nullable=True
    )
    pmerabrelabnormalenbactuelost_: Mapped[float] = mapped_column(
        Float(), nullable=True
    )
    pmbadcovevalreport_: Mapped[float] = mapped_column(Float(), nullable=True)
    cqi_bh: Mapped[float] = mapped_column(Float(), nullable=True)
    se_bh: Mapped[float] = mapped_column(Float(), nullable=True)


class HourlyLte(Base):
    __tablename__ = "hourly_lte"
    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    date_id: Mapped[date] = mapped_column(Date(), nullable=False)
    eutrancellfdd: Mapped[str] = mapped_column(Text(), nullable=False)
    hour_id: Mapped[int] = mapped_column(Integer(), nullable=False)
    rrc_setup_success_rate_service: Mapped[float] = mapped_column(
        Float(), nullable=True
    )
    e_e_rab_setup_success_rate_all: Mapped[float] = mapped_column(
        Float(), nullable=True
    )
    sessionsetupsuccessrate: Mapped[float] = mapped_column(Float(), nullable=True)
    sessionabnormalrelease: Mapped[float] = mapped_column(Float(), nullable=True)
    intra_intra_frequency_handover_out_success_rate: Mapped[float] = mapped_column(
        Float(), nullable=True
    )
    radio_network_availability_rate: Mapped[float] = mapped_column(
        Float(), nullable=True
    )
    cell_downlink_average_throughputmbps: Mapped[float] = mapped_column(
        Float(), nullable=True
    )
    cell_uplink_average_throughputmbps: Mapped[float] = mapped_column(
        Float(), nullable=True
    )
    dl_pdcp_user_throughput: Mapped[float] = mapped_column(Float(), nullable=True)
    user_downlink_average_throughput_mbps: Mapped[float] = mapped_column(
        Float(), nullable=True
    )
    user_uplink_average_throughputmbps: Mapped[float] = mapped_column(
        Float(), nullable=True
    )
    dl_resource_block_utilizing_rate: Mapped[float] = mapped_column(
        Float(), nullable=True
    )
    ul_resource_block_utilizing_rate: Mapped[float] = mapped_column(
        Float(), nullable=True
    )
    total_traff_volume: Mapped[float] = mapped_column(Float(), nullable=True)
    ul_int_pucch: Mapped[float] = mapped_column(Float(), nullable=True)
    maximum_user_number_rrc: Mapped[float] = mapped_column(Float(), nullable=True)
    max_dl_pdcp_user_throughput: Mapped[float] = mapped_column(Float(), nullable=True)
    max_user_uplink_average_throughput: Mapped[float] = mapped_column(
        Float(), nullable=True
    )
    l_latency_dl_ms: Mapped[float] = mapped_column(Float(), nullable=True)
    inter_freq_ho: Mapped[float] = mapped_column(Float(), nullable=True)
    ul_rssi_dbm: Mapped[float] = mapped_column(Float(), nullable=True)
    active_user: Mapped[float] = mapped_column(Float(), nullable=True)
    cqi_non_home: Mapped[float] = mapped_column(Float(), nullable=True)
    se: Mapped[float] = mapped_column(Float(), nullable=True)
    csfb_to_3g: Mapped[float] = mapped_column(Float(), nullable=True)
    cbra_sr: Mapped[float] = mapped_column(Float(), nullable=True)
    cbra_num: Mapped[float] = mapped_column(Float(), nullable=True)
    cbra_denum: Mapped[float] = mapped_column(Float(), nullable=True)
    qpsk_num: Mapped[float] = mapped_column(Float(), nullable=True)
    qpsk_denum: Mapped[float] = mapped_column(Float(), nullable=True)
    qam64_num: Mapped[float] = mapped_column(Float(), nullable=True)
    qam64_denum: Mapped[float] = mapped_column(Float(), nullable=True)
    pmrrcconnestabfailoverload: Mapped[float] = mapped_column(Float(), nullable=True)
    pmrrcconnestabfailhighload: Mapped[float] = mapped_column(Float(), nullable=True)
    pmerabestabfailinitlic: Mapped[float] = mapped_column(Float(), nullable=True)
    pmerabrelabnormalenbacttnfail: Mapped[float] = mapped_column(Float(), nullable=True)
    pmuectxtrelabnormalenbacttnfail: Mapped[float] = mapped_column(
        Float(), nullable=True
    )
    pmerabrelabnormalenbactho: Mapped[float] = mapped_column(Float(), nullable=True)
    pmuectxtrelabnormalenbactho: Mapped[float] = mapped_column(Float(), nullable=True)
    pmerabrelabnormalenbactuelost: Mapped[float] = mapped_column(Float(), nullable=True)
    pmuectxtrelabnormalenbactuelost: Mapped[float] = mapped_column(
        Float(), nullable=True
    )
    pmerabrelabnormalenbactcdt: Mapped[float] = mapped_column(Float(), nullable=True)
    pmuectxtrelabnormalenbactcdt: Mapped[float] = mapped_column(Float(), nullable=True)
    pmerabrelabnormalenbacthpr: Mapped[float] = mapped_column(Float(), nullable=True)
    pmbestcellevalreport: Mapped[float] = mapped_column(Float(), nullable=True)
    pmbadcovevalreport: Mapped[float] = mapped_column(Float(), nullable=True)
    pmmeasmissingneighrel: Mapped[float] = mapped_column(Float(), nullable=True)
    pmhopreprejinlicconnusers: Mapped[float] = mapped_column(Float(), nullable=True)
    pmhopreprejinlicrlcum: Mapped[float] = mapped_column(Float(), nullable=True)
    pmhopreprejinlicmultierab: Mapped[float] = mapped_column(Float(), nullable=True)
    pmrasucccfra: Mapped[float] = mapped_column(Float(), nullable=True)
    pmraattcfra: Mapped[float] = mapped_column(Float(), nullable=True)
    pmradiotbspwrrestricted: Mapped[float] = mapped_column(Float(), nullable=True)
    pmradiotbspwrunrestricted: Mapped[float] = mapped_column(Float(), nullable=True)
    pmlicconnectedusersmax: Mapped[float] = mapped_column(Float(), nullable=True)
    pmlicconnecteduserslicense: Mapped[float] = mapped_column(Float(), nullable=True)
    pmlicconnecteduserslevsamp: Mapped[float] = mapped_column(Float(), nullable=True)
    pmlicconnectedusersactual: Mapped[float] = mapped_column(Float(), nullable=True)
    pmlicconnecteduserslevsum: Mapped[float] = mapped_column(Float(), nullable=True)
    pmlicconnecteduserstimecong: Mapped[float] = mapped_column(Float(), nullable=True)
    s1_signaling_sr: Mapped[float] = mapped_column(Float(), nullable=True)
    intra_intra_frequency_handover_out_success_rate_num: Mapped[float] = mapped_column(
        Float(), nullable=True
    )
    intra_intra_frequency_handover_out_success_rate_denum: Mapped[float] = (
        mapped_column(Float(), nullable=True)
    )
    inter_freq_ho_num: Mapped[float] = mapped_column(Float(), nullable=True)
    inter_freq_ho_denum: Mapped[float] = mapped_column(Float(), nullable=True)
    pmrrcconnestabfailbeareradmissionrej: Mapped[float] = mapped_column(
        Float(), nullable=True
    )
    pmrrcconnestabfailcellintensdlc: Mapped[float] = mapped_column(
        Float(), nullable=True
    )
    pmrrcconnestabfailcellintensstat: Mapped[float] = mapped_column(
        Float(), nullable=True
    )
    pmrrcconnestabfailcellintensswc: Mapped[float] = mapped_column(
        Float(), nullable=True
    )
    pmrrcconnestabfailcelllatency: Mapped[float] = mapped_column(Float(), nullable=True)
    pmrrcconnestabfailduintens: Mapped[float] = mapped_column(Float(), nullable=True)
    pmrrcconnestabfailduswc: Mapped[float] = mapped_column(Float(), nullable=True)
    pmrrcconnestabfaildynueadmctrl: Mapped[float] = mapped_column(
        Float(), nullable=True
    )
    pmrrcconnestabfaillic: Mapped[float] = mapped_column(Float(), nullable=True)
    pmrrcconnestabfaillicactiveusers: Mapped[float] = mapped_column(
        Float(), nullable=True
    )
    pmrrcconnestabfaillowcovueadmctrl: Mapped[float] = mapped_column(
        Float(), nullable=True
    )
    pmrrcconnestabfaillowcovuelic: Mapped[float] = mapped_column(Float(), nullable=True)
    pmrrcconnestabfailmisigqcong: Mapped[float] = mapped_column(Float(), nullable=True)
    pmrrcconnestabfailmmeovlmod: Mapped[float] = mapped_column(Float(), nullable=True)
    pmrrcconnestabfailmmeovlmodce_: Mapped[float] = mapped_column(
        Float(), nullable=True
    )
    pmrrcconnestabfailmmeovlmos: Mapped[float] = mapped_column(Float(), nullable=True)
    pmrrcconnestabfailmmeovlmosce_: Mapped[float] = mapped_column(
        Float(), nullable=True
    )


class HourlyTwamp(Base):
    __tablename__ = "hourly_twamp"
    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    date_id: Mapped[date] = mapped_column(Date(), nullable=False)
    hour_id: Mapped[int] = mapped_column(Integer(), nullable=False)
    ne_name: Mapped[str] = mapped_column(Text(), nullable=False)
    packetlossratiofwd: Mapped[float] = mapped_column(Float(), nullable=True)
    packetlossratiorev: Mapped[float] = mapped_column(Float(), nullable=True)
    twamp_latency_avg: Mapped[float] = mapped_column(Float(), nullable=True)
    twamp_pl_avg: Mapped[float] = mapped_column(Float(), nullable=True)
    twamp_pl_max: Mapped[float] = mapped_column(Float(), nullable=True)
    sctp_packet_loss: Mapped[float] = mapped_column(Float(), nullable=True)


class DailyPagingLatency(Base):
    __tablename__ = "daily_paging_latency"
    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    date_id: Mapped[date] = mapped_column(Date(), nullable=False)
    erbs: Mapped[str] = mapped_column(Text(), nullable=False)
    site: Mapped[str] = mapped_column(Text(), nullable=False)
    ip_latency: Mapped[float] = mapped_column(Float(), nullable=True)
    pmpagdiscarded_: Mapped[float] = mapped_column(Float(), nullable=True)
    pmpagreceived_: Mapped[float] = mapped_column(Float(), nullable=True)
    paging_sr: Mapped[float] = mapped_column(Float(), nullable=True)
    paging_discard_rate: Mapped[float] = mapped_column(Float(), nullable=True)


class TaLte(Base):
    __tablename__ = "ta_lte"
    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    date_id: Mapped[date] = mapped_column(Date(), nullable=True)
    erbs: Mapped[str] = mapped_column(Text(), nullable=True)
    eutrancellfdd: Mapped[str] = mapped_column(Text(), nullable=True)
    dcvector_index: Mapped[int] = mapped_column(Integer(), nullable=True)
    pmtainit2distr: Mapped[float] = mapped_column(Float(), nullable=True)


class TaState(Base):
    __tablename__ = "ta_state"
    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    tanggal: Mapped[date] = mapped_column(Date(), nullable=True)
    site: Mapped[str] = mapped_column(Text(), nullable=True)
    enodebid: Mapped[int] = mapped_column(Integer(), nullable=True)
    ci: Mapped[int] = mapped_column(Integer(), nullable=True)
    avg_ta_km: Mapped[float] = mapped_column(Float(), nullable=True)
    std: Mapped[float] = mapped_column(Float(), nullable=True)
    perc50_ta_distance_km: Mapped[float] = mapped_column(Float(), nullable=True)
    perc80_ta_distance_km: Mapped[float] = mapped_column(Float(), nullable=True)
    perc85_ta_distance_km: Mapped[float] = mapped_column(Float(), nullable=True)
    perc90_ta_distance_km: Mapped[float] = mapped_column(Float(), nullable=True)
    perc95_ta_distance_km: Mapped[float] = mapped_column(Float(), nullable=True)
    perc97_5_ta_distance_km: Mapped[float] = mapped_column(Float(), nullable=True)
    perc98_ta_distance_km: Mapped[float] = mapped_column(Float(), nullable=True)
    perc98_6_ta_distance_km: Mapped[float] = mapped_column(Float(), nullable=True)
    perc99_ta_distance_km: Mapped[float] = mapped_column(Float(), nullable=True)
    perc99_5_ta_distance_km: Mapped[float] = mapped_column(Float(), nullable=True)
    perc99_9_ta_distance_km: Mapped[float] = mapped_column(Float(), nullable=True)
    perc_300: Mapped[float] = mapped_column(Float(), nullable=True)
    perc_500: Mapped[float] = mapped_column(Float(), nullable=True)
    perc_700: Mapped[float] = mapped_column(Float(), nullable=True)
    perc_1000: Mapped[float] = mapped_column(Float(), nullable=True)
    perc_1500: Mapped[float] = mapped_column(Float(), nullable=True)
    perc_2000: Mapped[float] = mapped_column(Float(), nullable=True)
    perc_3000: Mapped[float] = mapped_column(Float(), nullable=True)
    perc_5000: Mapped[float] = mapped_column(Float(), nullable=True)
    perc_10000: Mapped[float] = mapped_column(Float(), nullable=True)
    perc_15000: Mapped[float] = mapped_column(Float(), nullable=True)
    perc_30000: Mapped[float] = mapped_column(Float(), nullable=True)
    sample: Mapped[float] = mapped_column(Float(), nullable=True)
    ta0_78m: Mapped[float] = mapped_column(Float(), nullable=True)
    ta1_156m: Mapped[float] = mapped_column(Float(), nullable=True)
    ta2_234m: Mapped[float] = mapped_column(Float(), nullable=True)
    ta3_390m: Mapped[float] = mapped_column(Float(), nullable=True)
    ta4_546m: Mapped[float] = mapped_column(Float(), nullable=True)
    ta5_780m: Mapped[float] = mapped_column(Float(), nullable=True)
    ta6_1092m: Mapped[float] = mapped_column(Float(), nullable=True)
    ta7_1560m: Mapped[float] = mapped_column(Float(), nullable=True)
    ta8_2028m: Mapped[float] = mapped_column(Float(), nullable=True)
    ta9_2496m: Mapped[float] = mapped_column(Float(), nullable=True)
    ta10_2964m: Mapped[float] = mapped_column(Float(), nullable=True)
    ta11_3432m: Mapped[float] = mapped_column(Float(), nullable=True)
    ta12_3900m: Mapped[float] = mapped_column(Float(), nullable=True)
    ta13_4446m: Mapped[float] = mapped_column(Float(), nullable=True)
    ta14_6006m: Mapped[float] = mapped_column(Float(), nullable=True)
    ta15_gt_6006m: Mapped[float] = mapped_column(Float(), nullable=True)


class DailyVswr(Base):
    __tablename__ = "daily_vswr"
    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    date_id: Mapped[date] = mapped_column(Date(), nullable=True)
    ne_name: Mapped[str] = mapped_column(Text(), nullable=True)
    fieldreplaceableunit: Mapped[str] = mapped_column(Text(), nullable=True)
    moid: Mapped[str] = mapped_column(Text(), nullable=True)
    port_: Mapped[str] = mapped_column(Text(), nullable=True)
    rru: Mapped[str] = mapped_column(Text(), nullable=True)
    pmreturnlossavg: Mapped[float] = mapped_column(Float(), nullable=True)
    vswr: Mapped[float] = mapped_column(Float(), nullable=True)


class DailyGsm(Base):
    __tablename__ = "daily_gsm"
    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    bsc: Mapped[str] = mapped_column(Text(), nullable=True)
    ne_id: Mapped[str] = mapped_column(Text(), nullable=True)
    moid: Mapped[str] = mapped_column(Text(), nullable=True)
    date_id: Mapped[date] = mapped_column(Date(), nullable=True)
    cssr: Mapped[float] = mapped_column(Float(), nullable=True)
    scr: Mapped[float] = mapped_column(Float(), nullable=True)
    ra_suc: Mapped[float] = mapped_column(Float(), nullable=True)
    ra_tot: Mapped[float] = mapped_column(Float(), nullable=True)
    ra_loa_rej: Mapped[float] = mapped_column(Float(), nullable=True)
    ra_answpag: Mapped[float] = mapped_column(Float(), nullable=True)
    ra_service: Mapped[float] = mapped_column(Float(), nullable=True)
    ra_other: Mapped[float] = mapped_column(Float(), nullable=True)
    ra_emerg: Mapped[float] = mapped_column(Float(), nullable=True)
    ra_callree: Mapped[float] = mapped_column(Float(), nullable=True)
    s_cong: Mapped[float] = mapped_column(Float(), nullable=True)
    s_dr_c_ntc: Mapped[float] = mapped_column(Float(), nullable=True)
    s_traf: Mapped[float] = mapped_column(Float(), nullable=True)
    s_dr_ss: Mapped[float] = mapped_column(Float(), nullable=True)
    s_dr_bq: Mapped[float] = mapped_column(Float(), nullable=True)
    s_dr_ta: Mapped[float] = mapped_column(Float(), nullable=True)
    s_dr_oth: Mapped[float] = mapped_column(Float(), nullable=True)
    s_av_nr: Mapped[float] = mapped_column(Float(), nullable=True)
    s_avail: Mapped[float] = mapped_column(Float(), nullable=True)
    t_as_suc: Mapped[float] = mapped_column(Float(), nullable=True)
    tch_blocking: Mapped[float] = mapped_column(Float(), nullable=True)
    tch_traffic: Mapped[float] = mapped_column(Float(), nullable=True)
    th_traf: Mapped[float] = mapped_column(Float(), nullable=True)
    t_dr: Mapped[float] = mapped_column(Float(), nullable=True)
    new_tdr: Mapped[float] = mapped_column(Float(), nullable=True)
    t_dr_clm: Mapped[float] = mapped_column(Float(), nullable=True)
    t_dr_s: Mapped[float] = mapped_column(Float(), nullable=True)
    t_dr_ss_ul: Mapped[float] = mapped_column(Float(), nullable=True)
    t_dr_ss_dl: Mapped[float] = mapped_column(Float(), nullable=True)
    t_dr_ss_bl: Mapped[float] = mapped_column(Float(), nullable=True)
    t_dr_bq_ul: Mapped[float] = mapped_column(Float(), nullable=True)
    t_dr_bq_dl: Mapped[float] = mapped_column(Float(), nullable=True)
    t_dr_bq_bl: Mapped[float] = mapped_column(Float(), nullable=True)
    t_dr_sud: Mapped[float] = mapped_column(Float(), nullable=True)
    t_dr_ta: Mapped[float] = mapped_column(Float(), nullable=True)
    t_dr_oth: Mapped[float] = mapped_column(Float(), nullable=True)
    t_av_nr: Mapped[float] = mapped_column(Float(), nullable=True)
    t_avail: Mapped[float] = mapped_column(Float(), nullable=True)
    t_dwn: Mapped[float] = mapped_column(Float(), nullable=True)
    hot_suc: Mapped[float] = mapped_column(Float(), nullable=True)
    hot_rev: Mapped[float] = mapped_column(Float(), nullable=True)
    hot_lost: Mapped[float] = mapped_column(Float(), nullable=True)
    ho_suc: Mapped[float] = mapped_column(Float(), nullable=True)
    ho_rev: Mapped[float] = mapped_column(Float(), nullable=True)
    ho_lost: Mapped[float] = mapped_column(Float(), nullable=True)
    hoe_suc: Mapped[float] = mapped_column(Float(), nullable=True)
    hoe_rev: Mapped[float] = mapped_column(Float(), nullable=True)
    hoe_lost: Mapped[float] = mapped_column(Float(), nullable=True)
    hi_suc: Mapped[float] = mapped_column(Float(), nullable=True)
    hi_rev: Mapped[float] = mapped_column(Float(), nullable=True)
    hi_lost: Mapped[float] = mapped_column(Float(), nullable=True)
    ho_per_call: Mapped[float] = mapped_column(Float(), nullable=True)
    s_mht: Mapped[float] = mapped_column(Float(), nullable=True)
    t_cmht: Mapped[float] = mapped_column(Float(), nullable=True)
    cnrocnt: Mapped[float] = mapped_column(Float(), nullable=True)
    raaccfa: Mapped[float] = mapped_column(Float(), nullable=True)
    raemcal: Mapped[float] = mapped_column(Float(), nullable=True)
    racalre: Mapped[float] = mapped_column(Float(), nullable=True)
    raanpag: Mapped[float] = mapped_column(Float(), nullable=True)
    raosreq: Mapped[float] = mapped_column(Float(), nullable=True)
    raother: Mapped[float] = mapped_column(Float(), nullable=True)
    ratrhfaemcal: Mapped[float] = mapped_column(Float(), nullable=True)
    ratrhfaother: Mapped[float] = mapped_column(Float(), nullable=True)
    ratrhfareg: Mapped[float] = mapped_column(Float(), nullable=True)
    ratrhfaanpag: Mapped[float] = mapped_column(Float(), nullable=True)
    racalr1: Mapped[float] = mapped_column(Float(), nullable=True)
    racalr2: Mapped[float] = mapped_column(Float(), nullable=True)
    raapag1: Mapped[float] = mapped_column(Float(), nullable=True)
    raapag2: Mapped[float] = mapped_column(Float(), nullable=True)
    raapops: Mapped[float] = mapped_column(Float(), nullable=True)
    raorspe: Mapped[float] = mapped_column(Float(), nullable=True)
    raordat: Mapped[float] = mapped_column(Float(), nullable=True)
    csimmass: Mapped[float] = mapped_column(Float(), nullable=True)
    rejcsimmass: Mapped[float] = mapped_column(Float(), nullable=True)
    psimmass: Mapped[float] = mapped_column(Float(), nullable=True)
    rejpsimmass: Mapped[float] = mapped_column(Float(), nullable=True)
    ccongs: Mapped[float] = mapped_column(Float(), nullable=True)
    ccalls: Mapped[float] = mapped_column(Float(), nullable=True)
    cmsestab: Mapped[float] = mapped_column(Float(), nullable=True)
    cnrelcong: Mapped[float] = mapped_column(Float(), nullable=True)
    cndrop: Mapped[float] = mapped_column(Float(), nullable=True)
    cnuchcnt: Mapped[float] = mapped_column(Float(), nullable=True)
    ctralacc: Mapped[float] = mapped_column(Float(), nullable=True)
    cnscan: Mapped[float] = mapped_column(Float(), nullable=True)
    cavaacc: Mapped[float] = mapped_column(Float(), nullable=True)
    cavascan: Mapped[float] = mapped_column(Float(), nullable=True)
    cdisss: Mapped[float] = mapped_column(Float(), nullable=True)
    cdissssub: Mapped[float] = mapped_column(Float(), nullable=True)
    cdisqa: Mapped[float] = mapped_column(Float(), nullable=True)
    cdisqasub: Mapped[float] = mapped_column(Float(), nullable=True)
    cdista: Mapped[float] = mapped_column(Float(), nullable=True)
    tcassall: Mapped[float] = mapped_column(Float(), nullable=True)
    tfcassall: Mapped[float] = mapped_column(Float(), nullable=True)
    tfcassallsub: Mapped[float] = mapped_column(Float(), nullable=True)
    thcassall: Mapped[float] = mapped_column(Float(), nullable=True)
    thcassallsub: Mapped[float] = mapped_column(Float(), nullable=True)
    tassall: Mapped[float] = mapped_column(Float(), nullable=True)
    tfnrelcong: Mapped[float] = mapped_column(Float(), nullable=True)
    tfnrelcongsub: Mapped[float] = mapped_column(Float(), nullable=True)
    thnrelcong: Mapped[float] = mapped_column(Float(), nullable=True)
    thnrelcongsub: Mapped[float] = mapped_column(Float(), nullable=True)
    tftralacc: Mapped[float] = mapped_column(Float(), nullable=True)
    thtralacc: Mapped[float] = mapped_column(Float(), nullable=True)
    tfnscan: Mapped[float] = mapped_column(Float(), nullable=True)
    thnscan: Mapped[float] = mapped_column(Float(), nullable=True)
    tavaacc: Mapped[float] = mapped_column(Float(), nullable=True)
    tavascan: Mapped[float] = mapped_column(Float(), nullable=True)
    tnuchcnt: Mapped[float] = mapped_column(Float(), nullable=True)
    tndrop: Mapped[float] = mapped_column(Float(), nullable=True)
    tfndrop: Mapped[float] = mapped_column(Float(), nullable=True)
    tfndropsub: Mapped[float] = mapped_column(Float(), nullable=True)
    thndrop: Mapped[float] = mapped_column(Float(), nullable=True)
    thndropsub: Mapped[float] = mapped_column(Float(), nullable=True)
    tfdissul: Mapped[float] = mapped_column(Float(), nullable=True)
    tfdissulsub: Mapped[float] = mapped_column(Float(), nullable=True)
    thdissul: Mapped[float] = mapped_column(Float(), nullable=True)
    thdissulsub: Mapped[float] = mapped_column(Float(), nullable=True)
    tfdissdl: Mapped[float] = mapped_column(Float(), nullable=True)
    tfdissdlsub: Mapped[float] = mapped_column(Float(), nullable=True)
    thdissdl: Mapped[float] = mapped_column(Float(), nullable=True)
    thdissdlsub: Mapped[float] = mapped_column(Float(), nullable=True)
    tfdissbl: Mapped[float] = mapped_column(Float(), nullable=True)
    tfdissblsub: Mapped[float] = mapped_column(Float(), nullable=True)
    thdissbl: Mapped[float] = mapped_column(Float(), nullable=True)
    thdissblsub: Mapped[float] = mapped_column(Float(), nullable=True)
    tfdisqaul: Mapped[float] = mapped_column(Float(), nullable=True)
    tfdisqaulsub: Mapped[float] = mapped_column(Float(), nullable=True)
    thdisqaul: Mapped[float] = mapped_column(Float(), nullable=True)
    thdisqaulsub: Mapped[float] = mapped_column(Float(), nullable=True)
    tfdisqadl: Mapped[float] = mapped_column(Float(), nullable=True)
    tfdisqadlsub: Mapped[float] = mapped_column(Float(), nullable=True)
    thdisqadl: Mapped[float] = mapped_column(Float(), nullable=True)
    thdisqadlsub: Mapped[float] = mapped_column(Float(), nullable=True)
    tfdisqabl: Mapped[float] = mapped_column(Float(), nullable=True)
    tfdisqablsub: Mapped[float] = mapped_column(Float(), nullable=True)
    thdisqabl: Mapped[float] = mapped_column(Float(), nullable=True)
    thdisqablsub: Mapped[float] = mapped_column(Float(), nullable=True)
    tfsudlos: Mapped[float] = mapped_column(Float(), nullable=True)
    tfsudlossub: Mapped[float] = mapped_column(Float(), nullable=True)
    thsudlos: Mapped[float] = mapped_column(Float(), nullable=True)
    thsudlossub: Mapped[float] = mapped_column(Float(), nullable=True)
    tfdista: Mapped[float] = mapped_column(Float(), nullable=True)
    thdista: Mapped[float] = mapped_column(Float(), nullable=True)
    tdwnacc: Mapped[float] = mapped_column(Float(), nullable=True)
    tdwnscan: Mapped[float] = mapped_column(Float(), nullable=True)
    sumohosucc: Mapped[float] = mapped_column(Float(), nullable=True)
    sumohorev: Mapped[float] = mapped_column(Float(), nullable=True)
    sumoholost: Mapped[float] = mapped_column(Float(), nullable=True)
    sumohoatt: Mapped[float] = mapped_column(Float(), nullable=True)
    sumeohsucc: Mapped[float] = mapped_column(Float(), nullable=True)
    sumeohrev: Mapped[float] = mapped_column(Float(), nullable=True)
    sumeohlost: Mapped[float] = mapped_column(Float(), nullable=True)
    sumeohatt: Mapped[float] = mapped_column(Float(), nullable=True)
    sumihosucc: Mapped[float] = mapped_column(Float(), nullable=True)
    sumihorev: Mapped[float] = mapped_column(Float(), nullable=True)
    sumiholost: Mapped[float] = mapped_column(Float(), nullable=True)
    sumihoatt: Mapped[float] = mapped_column(Float(), nullable=True)
    sumiabsucc: Mapped[float] = mapped_column(Float(), nullable=True)
    sumiawsucc: Mapped[float] = mapped_column(Float(), nullable=True)
    sumoabsucc: Mapped[float] = mapped_column(Float(), nullable=True)
    sumoawsucc: Mapped[float] = mapped_column(Float(), nullable=True)
    tfmsestb: Mapped[float] = mapped_column(Float(), nullable=True)
    thmsestb: Mapped[float] = mapped_column(Float(), nullable=True)
    cssr_rs: Mapped[float] = mapped_column(Float(), nullable=True)
    ich_1: Mapped[float] = mapped_column(Float(), nullable=True)
    ich_2: Mapped[float] = mapped_column(Float(), nullable=True)
    ich_3: Mapped[float] = mapped_column(Float(), nullable=True)
    ich_4: Mapped[float] = mapped_column(Float(), nullable=True)
    ich_5: Mapped[float] = mapped_column(Float(), nullable=True)
    allpdchacc: Mapped[float] = mapped_column(Float(), nullable=True)
    allpdchscan: Mapped[float] = mapped_column(Float(), nullable=True)
    allpdchactacc: Mapped[float] = mapped_column(Float(), nullable=True)
    allocated_pdch: Mapped[float] = mapped_column(Float(), nullable=True)
    active_pdch_ratio: Mapped[float] = mapped_column(Float(), nullable=True)
    pdch_alloc_fail: Mapped[float] = mapped_column(Float(), nullable=True)
    pchallfail: Mapped[float] = mapped_column(Float(), nullable=True)
    pchallatt: Mapped[float] = mapped_column(Float(), nullable=True)
    gprs_throughput_dl: Mapped[float] = mapped_column(Float(), nullable=True)
    egprs_throughput_dl: Mapped[float] = mapped_column(Float(), nullable=True)
    gprs_throughput_ul: Mapped[float] = mapped_column(Float(), nullable=True)
    egprs_throughput_ul: Mapped[float] = mapped_column(Float(), nullable=True)
    payload_gprs_mbyte: Mapped[float] = mapped_column(Float(), nullable=True)
    payload_egprs_mbyte: Mapped[float] = mapped_column(Float(), nullable=True)
    data_payload: Mapped[float] = mapped_column(Float(), nullable=True)
    tbf_est_suc_ul: Mapped[float] = mapped_column(Float(), nullable=True)
    tbf_est_suc_dl: Mapped[float] = mapped_column(Float(), nullable=True)
    tbf_drop_dl: Mapped[float] = mapped_column(Float(), nullable=True)
    dltbfest: Mapped[float] = mapped_column(Float(), nullable=True)
    faildltbfest: Mapped[float] = mapped_column(Float(), nullable=True)
    pschreq: Mapped[float] = mapped_column(Float(), nullable=True)
    prejtfi: Mapped[float] = mapped_column(Float(), nullable=True)
    prejoth: Mapped[float] = mapped_column(Float(), nullable=True)
    ip_transfer_interupt_dl: Mapped[float] = mapped_column(Float(), nullable=True)
    tbfdlgprs: Mapped[float] = mapped_column(Float(), nullable=True)
    tbfdlegprs: Mapped[float] = mapped_column(Float(), nullable=True)
    ldisrr: Mapped[float] = mapped_column(Float(), nullable=True)
    fludisc: Mapped[float] = mapped_column(Float(), nullable=True)
    ldistfi: Mapped[float] = mapped_column(Float(), nullable=True)
    tf_traf_u: Mapped[float] = mapped_column(Float(), nullable=True)
    th_traf_u: Mapped[float] = mapped_column(Float(), nullable=True)
    tf_traf_o: Mapped[float] = mapped_column(Float(), nullable=True)
    th_traf_o: Mapped[float] = mapped_column(Float(), nullable=True)
    t_dr_ss_ul_u: Mapped[float] = mapped_column(Float(), nullable=True)
    t_dr_ss_dl_u: Mapped[float] = mapped_column(Float(), nullable=True)
    t_dr_ss_bl_u: Mapped[float] = mapped_column(Float(), nullable=True)
    t_dr_bq_ul_u: Mapped[float] = mapped_column(Float(), nullable=True)
    t_dr_bq_dl_u: Mapped[float] = mapped_column(Float(), nullable=True)
    t_dr_bq_bl_u: Mapped[float] = mapped_column(Float(), nullable=True)
    t_dr_sud_u: Mapped[float] = mapped_column(Float(), nullable=True)
    t_dr_oth_u: Mapped[float] = mapped_column(Float(), nullable=True)
    t_dr_ss_ul_o: Mapped[float] = mapped_column(Float(), nullable=True)
    t_dr_ss_dl_o: Mapped[float] = mapped_column(Float(), nullable=True)
    t_dr_ss_bl_o: Mapped[float] = mapped_column(Float(), nullable=True)
    t_dr_bq_ul_o: Mapped[float] = mapped_column(Float(), nullable=True)
    t_dr_bq_dl_o: Mapped[float] = mapped_column(Float(), nullable=True)
    t_dr_bq_bl_o: Mapped[float] = mapped_column(Float(), nullable=True)
    t_dr_sud_o: Mapped[float] = mapped_column(Float(), nullable=True)
    t_dr_oth_o: Mapped[float] = mapped_column(Float(), nullable=True)
    tbf_completion_rate: Mapped[float] = mapped_column(Float(), nullable=True)
    disnorm: Mapped[float] = mapped_column(Float(), nullable=True)
    pdch_congest: Mapped[float] = mapped_column(Float(), nullable=True)
    sqi_tot_good: Mapped[float] = mapped_column(Float(), nullable=True)
    sqi_tot_acceptable: Mapped[float] = mapped_column(Float(), nullable=True)
    sqi_tot_bad: Mapped[float] = mapped_column(Float(), nullable=True)
    rl_vol_gdl: Mapped[float] = mapped_column(Float(), nullable=True)
    rl_vol_gul: Mapped[float] = mapped_column(Float(), nullable=True)
    rl_vol_edl: Mapped[float] = mapped_column(Float(), nullable=True)
    rl_vol_eul: Mapped[float] = mapped_column(Float(), nullable=True)
    sdcch_success_rate: Mapped[float] = mapped_column(Float(), nullable=True)
    cestimmass: Mapped[float] = mapped_column(Float(), nullable=True)
    preemptpdch: Mapped[float] = mapped_column(Float(), nullable=True)
    tbf_establishment_sr: Mapped[float] = mapped_column(Float(), nullable=True)
    num_sdsr: Mapped[float] = mapped_column(Float(), nullable=True)
    denum_sdsr: Mapped[float] = mapped_column(Float(), nullable=True)
    num_new_sdsr: Mapped[float] = mapped_column(Float(), nullable=True)
    denum_nem_sdsr: Mapped[float] = mapped_column(Float(), nullable=True)
    num_hosr: Mapped[float] = mapped_column(Float(), nullable=True)
    denum_hosr: Mapped[float] = mapped_column(Float(), nullable=True)
    num_dcr: Mapped[float] = mapped_column(Float(), nullable=True)
    denum_dcr: Mapped[float] = mapped_column(Float(), nullable=True)
    num_new_dcr: Mapped[float] = mapped_column(Float(), nullable=True)
    denum_new_dcr: Mapped[float] = mapped_column(Float(), nullable=True)
    num_tbf_dl_success_rate: Mapped[float] = mapped_column(Float(), nullable=True)
    denum_tbf_dl_success_rate: Mapped[float] = mapped_column(Float(), nullable=True)
    num_tbf_comp_rate: Mapped[float] = mapped_column(Float(), nullable=True)
    denum_tbf_comp_rate: Mapped[float] = mapped_column(Float(), nullable=True)
    num_s_cong: Mapped[float] = mapped_column(Float(), nullable=True)
    denum_s_cong: Mapped[float] = mapped_column(Float(), nullable=True)
    num_t_cong: Mapped[float] = mapped_column(Float(), nullable=True)
    denum_t_cong: Mapped[float] = mapped_column(Float(), nullable=True)
    num_gprs_throughput_dl: Mapped[float] = mapped_column(Float(), nullable=True)
    denum_gprs_throughput_dl: Mapped[float] = mapped_column(Float(), nullable=True)
    num_egprs_throughput_dl: Mapped[float] = mapped_column(Float(), nullable=True)
    denum_egprs_throughput_dl: Mapped[float] = mapped_column(Float(), nullable=True)
    num_gprs_throughput_ul: Mapped[float] = mapped_column(Float(), nullable=True)
    denum_gprs_throughput_ul: Mapped[float] = mapped_column(Float(), nullable=True)
    num_egprs_throughput_ul: Mapped[float] = mapped_column(Float(), nullable=True)
    denum_egprs_throughput_ul: Mapped[float] = mapped_column(Float(), nullable=True)
    dcr: Mapped[float] = mapped_column(Float(), nullable=True)
    new_dcr: Mapped[float] = mapped_column(Float(), nullable=True)
    thncedrop: Mapped[float] = mapped_column(Float(), nullable=True)
    tfncedrop: Mapped[float] = mapped_column(Float(), nullable=True)
    num_t_avail: Mapped[float] = mapped_column(Float(), nullable=True)
    denum_t_avail: Mapped[float] = mapped_column(Float(), nullable=True)
    parlen: Mapped[float] = mapped_column(Float(), nullable=True)
    preempttbf: Mapped[float] = mapped_column(Float(), nullable=True)
    movecelltbf: Mapped[float] = mapped_column(Float(), nullable=True)
    iaulrel: Mapped[float] = mapped_column(Float(), nullable=True)
    preemptulrel: Mapped[float] = mapped_column(Float(), nullable=True)
    othulrel: Mapped[float] = mapped_column(Float(), nullable=True)
    ldisrr_: Mapped[float] = mapped_column(Float(), nullable=True)
    ldisoth: Mapped[float] = mapped_column(Float(), nullable=True)
    dltbfest_: Mapped[float] = mapped_column(Float(), nullable=True)
    faildltbfest_: Mapped[float] = mapped_column(Float(), nullable=True)
    faildlansw: Mapped[float] = mapped_column(Float(), nullable=True)
    msestultbf: Mapped[float] = mapped_column(Float(), nullable=True)
    rxq_050_dl: Mapped[float] = mapped_column(Float(), nullable=True)
    rxq_050_ul: Mapped[float] = mapped_column(Float(), nullable=True)
    qual50dl: Mapped[float] = mapped_column(Float(), nullable=True)
    qual50ul: Mapped[float] = mapped_column(Float(), nullable=True)
    tbf_dl_establishment_sr_num: Mapped[float] = mapped_column(Float(), nullable=True)
    tbf_dl_establishment_sr_denum: Mapped[float] = mapped_column(Float(), nullable=True)
    tbf_ul_est_sr_num: Mapped[float] = mapped_column(Float(), nullable=True)
    tbf_ul_est_sr_denum: Mapped[float] = mapped_column(Float(), nullable=True)
    gprs_payload_mbyte: Mapped[float] = mapped_column(Float(), nullable=True)
    edge_payload_mbyte: Mapped[float] = mapped_column(Float(), nullable=True)
    gprs_throughput_kbps: Mapped[float] = mapped_column(Float(), nullable=True)
    edge_throughput_kbps: Mapped[float] = mapped_column(Float(), nullable=True)
    csfb_sr: Mapped[float] = mapped_column(Float(), nullable=True)


class PacketLossGsm(Base):
    __tablename__ = "pl_gsm"
    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    date_id: Mapped[date] = mapped_column(Date(), nullable=True)
    bts: Mapped[str] = mapped_column(Text(), nullable=True)
    gsmsector: Mapped[str] = mapped_column(Text(), nullable=True)
    pml2tplostpack_: Mapped[float] = mapped_column(Float(), nullable=True)
    pml2tprecpack_: Mapped[float] = mapped_column(Float(), nullable=True)
    pml2tpsentpack_: Mapped[float] = mapped_column(Float(), nullable=True)
    packetlost: Mapped[float] = mapped_column(Float(), nullable=True)


class MrrGSM(Base):
    __tablename__ = "mrr_gsm"
    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    bsc: Mapped[str] = mapped_column(Text(), nullable=True)
    site: Mapped[str] = mapped_column(Text(), nullable=True)
    gerancell: Mapped[str] = mapped_column(Text(), nullable=True)
    ta_550m: Mapped[float] = mapped_column(Float(), nullable=True)
    ta_1100m: Mapped[float] = mapped_column(Float(), nullable=True)
    ta_2200m: Mapped[float] = mapped_column(Float(), nullable=True)
    ta_3300m: Mapped[float] = mapped_column(Float(), nullable=True)
    ta_5500m: Mapped[float] = mapped_column(Float(), nullable=True)
    ta_10450m: Mapped[float] = mapped_column(Float(), nullable=True)
    ta_15400m: Mapped[float] = mapped_column(Float(), nullable=True)
    ta_more_than_15400m: Mapped[float] = mapped_column(Float(), nullable=True)
    perc_550m: Mapped[float] = mapped_column(Float(), nullable=True)
    perc_1100m: Mapped[float] = mapped_column(Float(), nullable=True)
    perc_2200m: Mapped[float] = mapped_column(Float(), nullable=True)
    perc_3300m: Mapped[float] = mapped_column(Float(), nullable=True)
    perc_5500m: Mapped[float] = mapped_column(Float(), nullable=True)
    perc_10450m: Mapped[float] = mapped_column(Float(), nullable=True)
    perc_15400m: Mapped[float] = mapped_column(Float(), nullable=True)
    perc_more_than_15400m: Mapped[float] = mapped_column(Float(), nullable=True)
    perc_50th_km: Mapped[float] = mapped_column(Float(), nullable=True)
    perc_80th_km: Mapped[float] = mapped_column(Float(), nullable=True)


# class ServiceBase(DeclarativeBase):
#     metadata = MetaData(schema="service")
